# Generated by Django 5.0.2 on 2024-02-17 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mamma_Mia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='composition',
        ),
        migrations.AddField(
            model_name='courier',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='instruments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(default='Russia', max_length=100),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
