# Generated by Django 5.0.2 on 2024-03-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mamma_Mia', '0005_ingredient_role_topping_remove_order_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mamma_Mia.rol'),
        ),
    ]
