# Generated by Django 5.0.2 on 2024-03-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mamma_Mia', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
