# Generated by Django 5.0.2 on 2024-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mamma_Mia', '0007_remove_userprofile_rol_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
