# Generated by Django 5.0.2 on 2024-03-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mamma_Mia', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
